[project]
name = "asebytes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ase>=3.26.0",
    "lmdb>=1.7.5",
    "msgpack>=1.1.2",
    "msgpack-numpy>=0.4.8",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "molify>=0.0.1a0",
    "pytest>=8.4.2",
]
